"""add_stripe_customer_id_to_users

Revision ID: 93fdf14be379
Revises: initial_001
Create Date: 2026-01-15 17:57:01.254961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93fdf14be379'
down_revision = 'initial_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_preset_configs_name', table_name='preset_configs')
    op.create_unique_constraint(None, 'preset_configs', ['name'])
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.drop_index('ix_users_google_id', table_name='users')
    op.create_unique_constraint(None, 'users', ['google_id'])
    op.create_unique_constraint(None, 'users', ['stripe_customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=False)
    op.drop_column('users', 'stripe_customer_id')
    op.drop_constraint(None, 'preset_configs', type_='unique')
    op.create_index('ix_preset_configs_name', 'preset_configs', ['name'], unique=False)
    # ### end Alembic commands ###